import { test, expect } from '@playwright/test';

// Testing full lesson completion flow

test('italian lesson completed', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.locator('#radix-_r_3_').click();
  await page.getByRole('menuitem', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('newUser');
  await page.getByRole('textbox', { name: 'Password' }).fill('newPassword');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#radix-_r_n_').click();
  await page.getByRole('link', { name: 'Lessons', exact: true }).click();
  await page.locator('html').click();
  await page.getByRole('link', { name: 'Lesson 1 Greetings and' }).click();
  await page.getByRole('textbox', { name: 'Answer Answer Answer Answer' }).scrollIntoViewIfNeeded();
  await page.getByRole('textbox', { name: 'Answer Answer Answer Answer' }).fill('sono');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('chiami');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('siamo');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('si');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('tu');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('è');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('sono');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('si');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('loro');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('io');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('radio', { name: 'Ciao' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Where are you from?' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Mi chiamo Luca' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Lei è' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Noi siamo studenti' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('label').filter({ hasText: 'Come si chiama?' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'siete' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'And you?' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'In formal situations' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Nice to meet you too' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('Exercises complete.')).toBeVisible();
});

test('french lesson completed', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.locator('#radix-_r_3_').click();
  await page.getByRole('menuitem', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('newUser');
  await page.getByRole('textbox', { name: 'Password' }).fill('newPassword');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('#radix-_r_n_').click();
  await page.getByRole('link', { name: 'Lessons', exact: true }).click();
  await page.locator('html').click();
  await page.getByText('Italian', { exact: true }).click();
  await page.getByRole('option', { name: 'French' }).click();
  await page.getByRole('link', { name: 'Lesson 1 Greetings and' }).click();
  await page.getByRole('textbox', { name: 'Answer Answer Answer Answer' }).fill('Salut');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('vous');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('suis');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('comment');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('Enchanté');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('Au');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('es');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('américain');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('Très');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('textbox', { name: 'Type your answer…' }).fill('toi');
  await page.getByRole('button', { name: 'Check' }).click();
  await page.getByRole('radio', { name: 'Bonjour' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Je m\'appelle...' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'suis' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'With a professor' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Comment vous appelez-vous?' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'française', exact: true }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Nice to meet you' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Je suis du Canada' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Ça va bien' }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('radio', { name: 'Il est italien', exact: true }).check();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('Exercises complete.')).toBeVisible();
});